package com.app.entity;

public enum Specialization {
	STRENGTH_AND_CONDITIONING,
    CARDIOVASCULAR_FITNESS,
    WEIGHT_MANAGEMENT,
    SPORTS_SPECIFIC,
    YOGA_AND_PILATES,
    GROUP_FITNESS,
    REHABILITATION_AND_INJURY_PREVENTION,
    NUTRITION_AND_DIET_COACHING,
    MIND_BODY_WELLNESS,
    SENIOR_FITNESS,
    PRE_AND_POSTNATAL_FITNESS,
    GENERAL_TRAINING
}
